name: main
on:
  pull_request:
    branches:
    - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7
    - run: terraform fmt -check -recursive
